language: ruby
rvm:
- 2.0.0
env:
- DB=postgresql
before script:
- psql -c 'create database dchiv_development;' -U postgres
script:
- bundle exec rake db:migrate
deploy:
  provider: heroku
  strategy: git
  api_key:
    secure: QKxCTORANVjxM4uAo4/+dKAX8QehW9E3Ywms9f2O41eimovNp5ACZmxZYeG4HSqjPTQ3YZlL1Sh5imTpd79m7B7DhPHgaGdY+qJu8xQcX9eJ43nlONrqfgFe0FswplHpkX/PtsJ9YXRa9x35RrIU6GQi1Ak1ng2vQSxx8JiwCgc=
  run:
   - "rake db:migrate"
   - restart
