development:
  adapter: sqlite3
  database: db/development.sqlite3 
  pool: 5
  
test:
  adapter: sqlite3
  database: db/dchiv_test
  pool: 5
  
production:
  adapter: sqlite3
  database: db/dchiv_production
  pool: 5
  
