development:
  adapter: postgresql
  database: dchiv_development
  encoding: unicode
  pool: 5
  username: postgres
  
test:
  adapter: postgresql
  database: dchiv_test
  encoding: unicode
  pool: 5
  username: postgres
 
production:
  adapter: postgresql
  database: dchiv_production
  encoding: unicode
  pool: 5
  username: postgres
