development:
  adapter: postgresql
  database: dchiv_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: dchiv_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: dchiv_production
  pool: 5
  timeout: 5000
